version: "3"

services:
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "8080:80"
    networks:
      - challenge

  node:
    container_name: node
    build:
      context: .
    volumes:
      - ./app:/src/app
    expose:
      - "3333"
    tty: true
    networks:
      - challenge
    depends_on:
      - mysql

  mysql:
    container_name: mysql
    image: mysql
    command: --innodb-use-native-aio=0
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_USER=challenge
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=challenge
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - challenge

networks:
  challenge:
    driver: bridge
